### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by mm333444** [Ouroboros/GoLibs#2]
你好, 无意中看到您的代码, 但是遇到点小问题, 能否加您QQ
我QQ：2387183033
谢谢阿！

**Comment by Ouroboros** [comment]
什么问题

**Comment by mm333444** [comment]
我自己写了一个test.go
引用了您代码里itunes/login.go
但是执行go run test.go
提示
# ml/syscall
ml/syscall/syscall.go:6: undefined: Call

顺便和您确认一下
您代码里的itunes/login.go 是模拟登陆itunes账号的代码么？
非常抱歉，我没学过go语言，只能简单看懂一点点

**Comment by Ouroboros** [comment]
那你先去学go吧

**Comment by mm333444** [comment]
能否告诉我这段代码的运行环境? 非常感谢，剩下的问题我会自己学习解决
